import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||new URL('../../ui/node_modules/playwright/index.mjs',import.meta.url).href);
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},locale:'fr-FR'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('422'))errors.push(m.text());});
const base=process.env.SEARCHMYJOB_TEST_URL||'http://127.0.0.1:8965';
await page.goto(base);await page.getByRole('heading',{name:'Connecte ton assistant IA'}).waitFor();
assert.equal(await page.getByRole('button',{name:'Continuer',exact:true}).isDisabled(),true);
await page.getByLabel('Clé API',{exact:true}).fill('bad-key');
await page.getByLabel('Identifiant du modèle').fill('gpt-fixture');
await page.getByRole('button',{name:'Tester et enregistrer'}).click();
await page.getByRole('alert').filter({hasText:'Clé API refusée'}).waitFor();
assert.equal(await page.getByRole('button',{name:'Continuer',exact:true}).isDisabled(),true);
await page.getByLabel('Clé API',{exact:true}).fill('fixture-key');
await page.getByRole('button',{name:'Charger les modèles'}).click();
await page.getByLabel('Modèles proposés').selectOption('gpt-fixture');
await page.getByRole('button',{name:'Tester et enregistrer'}).click();
await page.getByText('Connexion et appel d’outil validés.',{exact:false}).waitFor();
assert.equal(await page.getByLabel('Clé API',{exact:true}).inputValue(),'');
assert.equal(await page.getByRole('button',{name:'Continuer',exact:true}).isEnabled(),true);
await page.reload();await page.getByText('Ce fournisseur a déjà été testé',{exact:false}).waitFor();
assert.equal(await page.getByRole('button',{name:'Continuer',exact:true}).isEnabled(),true);
await page.getByLabel('Fournisseur IA',{exact:true}).selectOption('claude');
assert.equal(await page.getByRole('button',{name:'Continuer',exact:true}).isDisabled(),true);
await page.getByLabel('Fournisseur IA',{exact:true}).selectOption('openai');
await page.getByRole('button',{name:'Continuer',exact:true}).click();
await page.getByRole('heading',{name:'Choisis tes sources de recherche'}).waitFor();
await page.getByLabel('Pays de recherche',{exact:true}).selectOption('it');
await page.getByLabel('Métier / mots-clés',{exact:true}).fill('Cuoco');
await page.getByLabel('Source',{exact:true}).selectOption('bright');
await page.getByLabel('Clé Bright Data',{exact:true}).fill('fixture-source-key');
await page.getByRole('button',{name:'Enregistrer cette source'}).click();
await page.getByText('Identifiants enregistrés. Aucune recherche effectuée.').waitFor();
await page.getByRole('button',{name:'Continuer',exact:true}).click();
await page.getByLabel('Ton parcours et tes compétences').fill('Profil de test navigateur');
await page.getByRole('button',{name:'Activer mon espace'}).click();
await page.getByLabel('Ton message',{exact:true}).waitFor();
await page.getByLabel('Ton message',{exact:true}).fill('Bonjour');
await page.getByRole('button',{name:'Envoyer',exact:true}).click();
await page.getByText('Réponse de test : ton espace fonctionne.',{exact:true}).waitFor();
await page.reload();await page.getByText('Réponse de test : ton espace fonctionne.',{exact:true}).waitFor();
for(const width of [1440,390]){
 await page.setViewportSize({width,height:900});
 await page.waitForTimeout(300);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
}
const data=await page.evaluate(async()=>({state:await (await fetch('/api/state')).json(),ai:await(await fetch('/api/ai')).json()}));
assert.equal(data.state.settings.enabled,false);
assert(!JSON.stringify(data).includes('fixture-key'));
assert.equal(data.state.profile,'Profil de test navigateur');
assert.equal(data.state.criteria.country,'it');
assert.equal(data.state.criteria.source,'bright');
assert.deepEqual(data.state.criteria.platforms,['linkedin','indeed']);
assert.deepEqual(errors,[]);
await browser.close();
console.log('Parcours navigateur validé : erreur clé, catalogue, test, rechargement, séparation sources, activation, chat, mobile.');
