import { reactive } from 'vue';
import { initializeWorkspaceState } from './workspace/state.js';
import { registerConversation } from '../features/conversation/controller.js';
import { registerLayout } from '../features/layout/controller.js';
import { registerProfile } from '../features/profile/controller.js';
import { registerOpportunities } from '../features/opportunities/controller.js';
import { registerDocuments } from '../features/documents/controller.js';
import { registerMail } from '../features/mail/controller.js';
import { registerMemory } from '../features/memory/controller.js';
import { registerMonitoring } from '../features/monitoring/controller.js';
import { registerWorkspace } from '../features/workspace/controller.js';
export function useWorkspace() {
  const ctx = {};
  const effects = [
    registerConversation(ctx),
    registerLayout(ctx),
    registerProfile(ctx),
    registerOpportunities(ctx),
    registerDocuments(ctx),
    registerMail(ctx),
    registerMemory(ctx),
    registerMonitoring(ctx),
    registerWorkspace(ctx),
  ];
  initializeWorkspaceState(ctx);
  ctx.registerMessageList = (element) => {
    ctx.messageLists.value = element ? [element] : [];
  };
  effects.forEach((start) => start());
  const views = {
    AppSidebar: reactive({
      tab: ctx.tab,
      profile: ctx.profile,
      pages: ctx.pages,
      collapsed: ctx.collapsed,
      navigate: ctx.navigate,
      offers: ctx.offers,
      counts: ctx.counts,
    }),
    AppHeader: reactive({
      state: ctx.state,
      selected: ctx.selected,
      modes: ctx.modes,
      themes: ctx.themes,
      theme: ctx.theme,
      pageWidth: ctx.pageWidth,
      agentWidth: ctx.agentWidth,
      layoutMode: ctx.layoutMode,
      changeLayout: ctx.changeLayout,
      showTasks: ctx.showTasks,
      showLayouts: ctx.showLayouts,
      forceSidebar: ctx.forceSidebar,
      sidebarHidden: ctx.sidebarHidden,
      navigate: ctx.navigate,
      busy: ctx.busy,
      memoryStatus: ctx.memoryStatus,
    }),
    WorkspaceTabs: reactive({
      tab: ctx.tab,
      selected: ctx.selected,
      pages: ctx.pages,
      openedTabs: ctx.openedTabs,
      sidebarHidden: ctx.sidebarHidden,
      navigate: ctx.navigate,
      closeTab: ctx.closeTab,
      moveTab: ctx.moveTab,
    }),
    conversation: reactive({
      conversationId: ctx.conversationId,
      conversationArchived: ctx.conversationArchived,
      conversationBusy: ctx.conversationBusy,
      chooseConversation: ctx.chooseConversation,
      newConversation: ctx.newConversation,
      resetConversation: ctx.resetConversation,
      renameConversation: ctx.renameConversation,
      state: ctx.state,
      settings: ctx.settings,
      profile: ctx.profile,
      draft: ctx.draft,
      provider: ctx.provider,
      loading: ctx.loading,
      filter: ctx.filter,
      timer: ctx.timer,
      quickPrompts: ctx.quickPrompts,
      preparePrompt: ctx.preparePrompt,
      openBeside: ctx.openBeside,
      showTasks: ctx.showTasks,
      recentTasks: ctx.recentTasks,
      navigate: ctx.navigate,
      busy: ctx.busy,
      taskPhase: ctx.taskPhase,
      elapsedTime: ctx.elapsedTime,
      offers: ctx.offers,
      counts: ctx.counts,
      date: ctx.date,
      statusText: ctx.statusText,
      api: ctx.api,
      action: ctx.action,
      send: ctx.send,
      saveDraft: ctx.saveDraft,
      search: ctx.search,
      registerMessageList: ctx.registerMessageList,
    }),
    offers: reactive({
      state: ctx.state,
      criteria: ctx.criteria,
      loading: ctx.loading,
      filter: ctx.filter,
      resultType: ctx.resultType,
      query: ctx.query,
      offerDetail: ctx.offerDetail,
      showSearch: ctx.showSearch,
      quickPrompts: ctx.quickPrompts,
      preparePrompt: ctx.preparePrompt,
      busy: ctx.busy,
      offers: ctx.offers,
      counts: ctx.counts,
      date: ctx.date,
      api: ctx.api,
      action: ctx.action,
      search: ctx.search,
      generate: ctx.generate,
      mail: ctx.mail,
    }),
    profile: reactive({
      state: ctx.state,
      profile: ctx.profile,
      draft: ctx.draft,
      loading: ctx.loading,
      editingProfile: ctx.editingProfile,
      profileDirty: ctx.profileDirty,
      profileTitle: ctx.profileTitle,
      brief: ctx.brief,
      saveProfile: ctx.saveProfile,
      importCV: ctx.importCV,
    }),
    documents: reactive({
      tab: ctx.tab,
      state: ctx.state,
      selected: ctx.selected,
      docText: ctx.docText,
      docApproved: ctx.docApproved,
      busy: ctx.busy,
      offers: ctx.offers,
      date: ctx.date,
      api: ctx.api,
      action: ctx.action,
      mail: ctx.mail,
      emailFromDoc: ctx.emailFromDoc,
      editDoc: ctx.editDoc,
    }),
    heartbeat: reactive({
      state: ctx.state,
      settings: ctx.settings,
      loading: ctx.loading,
      navigate: ctx.navigate,
      busy: ctx.busy,
      api: ctx.api,
      action: ctx.action,
      mail: ctx.mail,
    }),
    mail: reactive({
      state: ctx.state,
      error: ctx.error,
      selected: ctx.selected,
      credentials: ctx.credentials,
      navigate: ctx.navigate,
      busy: ctx.busy,
      offers: ctx.offers,
      date: ctx.date,
      api: ctx.api,
      action: ctx.action,
      send: ctx.send,
      mailForm: ctx.mailForm,
      mailSelected: ctx.mailSelected,
      mailConfirm: ctx.mailConfirm,
      senderName: ctx.senderName,
      emails: ctx.emails,
      mail: ctx.mail,
      openEmail: ctx.openEmail,
      connectMail: ctx.connectMail,
      saveEmail: ctx.saveEmail,
      sendEmail: ctx.sendEmail,
      discardEmail: ctx.discardEmail,
      newEmail: ctx.newEmail,
    }),
    connections: reactive({
      state: ctx.state,
    }),
  };
  return {
    ...ctx,
    views,
  };
}
